DO $outer$
DECLARE
  v_data1 jsonb;
BEGIN
  ALTER TABLE public.weekly_reports DISABLE TRIGGER trg_weekly_reports_set_fields;

  -- Week 1
  UPDATE public.weekly_reports SET data = data
    || jsonb_build_object(
      'lookaheadTasks', '[{"id":"553f9473-8d84-4906-9d3d-2758624221e6","date":"2026-01-26","description":"Desmobilização de móveis e objetos do apartamento para área de descarte e proteção.","prerequisites":"Definição final dos itens a serem descartados pelo cliente.","responsible":"Equipe de Apoio / Empreiteira","risk":"baixo","riskReason":"Atividade de baixa complexidade com equipe dedicada."},{"id":"3efc9a17-fec7-4c88-afbc-aadabdbdf272","date":"2026-01-27","description":"Proteção de áreas comuns do condomínio (elevador, halls, rotas de transporte de material).","prerequisites":"Aprovação do condomínio.","responsible":"Equipe de Apoio / Empreiteira","risk":"médio","riskReason":"Atenção a detalhes para evitar danos e reclamações do condomínio."},{"id":"81d06ebc-c1fd-4602-9661-7d707510ea22","date":"2026-01-28","description":"Início da demolição controlada de forros de gesso e paredes de drywall conforme projeto aprovado.","prerequisites":"Apartamento desmobilizado e áreas comuns protegidas.","responsible":"Equipe de Demolição","risk":"médio","riskReason":"Possibilidade de encontrar infraestrutura não mapeada e geração de ruído."},{"id":"b683a44b-f490-4b83-bcb1-7bdd810bbd08","date":"2026-01-29","description":"Remoção e descarte de louças e metais sanitários existentes nos banheiros e cozinha.","prerequisites":"Desmobilização interna concluída.","responsible":"Equipe de Demolição","risk":"baixo","riskReason":"Atividade rotineira."},{"id":"192039cb-370d-48d1-a661-165912633bc2","date":"2026-01-30","description":"Levantamento fotográfico detalhado das condições pré-demolição de todas as áreas afetadas.","prerequisites":"Apartamento desmobilizado.","responsible":"Engenheiro Residente","risk":"baixo","riskReason":"Atividade de registro documental."}]'::jsonb,
      'risksAndIssues', '[{"id":"3d005187-2a56-4e28-b39e-7b4cca6aca5f","type":"risco","title":"Atraso na aprovação de projeto pelo condomínio","description":"Potenciais atrasos na aprovação de projetos executivos ou na liberação de horários para serviços ruidosos.","impact":{"time":"médio","cost":"baixo","quality":"baixo"},"severity":"média","actionPlan":"Manter contato proativo e documentado com a administração do condomínio.","owner":"Engenheiro Residente","dueDate":"2026-01-28","status":"aberto"},{"id":"3d0c3af9-8bd0-4a34-870c-f70d0bf49786","type":"impedimento","title":"Atraso em materiais de proteção","description":"Fornecedor informou pequeno atraso na entrega dos materiais de proteção, nova previsão para 27/01.","impact":{"time":"baixo","cost":"baixo","quality":"baixo"},"severity":"baixa","actionPlan":"Confirmar nova data com fornecedor e acionar fornecedor secundário se necessário.","owner":"Engenheiro Residente","dueDate":"2026-01-26","status":"em acompanhamento"}]'::jsonb,
      'clientDecisions', '[]'::jsonb
    )
    WHERE project_id = 'fc1eb067-a7d9-41e1-bd39-1845e750c3b7' AND week_number = 1;

  -- Week 2
  UPDATE public.weekly_reports SET data = data
    || jsonb_build_object(
      'lookaheadTasks', '[{"id":"8a57d300-098d-42a0-bcad-24cfd1b5be1a","date":"2026-02-03","description":"Verificação e aprovação final dos ajustes de instalações elétricas (pontos de iluminação e tomadas).","prerequisites":"Execução completa dos ajustes elétricos.","responsible":"Equipe de Elétrica","risk":"baixo","riskReason":"Atividade de verificação rotineira."},{"id":"cf653047-06a2-446a-a01f-f797a6781ac7","date":"2026-02-04","description":"Limpeza e preparação das superfícies para recebimento da equipe de gesso.","prerequisites":"Conclusão das instalações elétricas.","responsible":"Equipe de Apoio","risk":"baixo","riskReason":"Atividade de apoio."},{"id":"2688ded0-e6bd-49e3-9ced-84e2eba3deb6","date":"2026-02-05","description":"Início da execução de forro de gesso e sancas nos ambientes principais.","prerequisites":"Superfícies preparadas; materiais e equipe de gesso mobilizados.","responsible":"Equipe de Gesso","risk":"médio","riskReason":"Atraso na liberação da frente de serviço ou falta de material."},{"id":"d0639279-0ba3-45d1-adcf-c10a3c36bfe9","date":"2026-02-07","description":"Verificação da conformidade da execução do gesso com o projeto e nivelamento.","prerequisites":"Avanço significativo na execução do gesso.","responsible":"Engenheiro Residente","risk":"médio","riskReason":"Identificação tardia de não conformidades pode gerar retrabalho."}]'::jsonb,
      'risksAndIssues', '[{"id":"4fd999a4-181e-475a-9d78-45886f3c1cfc","type":"problema","title":"Não conformidade em pontos de iluminação","description":"Necessidade de realocação de 2 pontos de iluminação na sala por não atenderem ao layout do mobiliário.","impact":{"time":"baixo","cost":"baixo","quality":"médio"},"severity":"média","actionPlan":"Ajuste imediato dos pontos pelos eletricistas e revalidação com o arquiteto.","owner":"Engenheiro Residente","dueDate":"2026-02-02","status":"em acompanhamento"},{"id":"00372989-8b77-4bca-9609-aa564390a184","type":"risco","title":"Atraso na entrega de materiais de gesso","description":"Fornecedor alertou sobre potencial atraso de 1-2 dias na entrega dos perfis metálicos para o forro de gesso.","impact":{"time":"médio","cost":"baixo","quality":"baixo"},"severity":"média","actionPlan":"Monitoramento diário com o fornecedor e fornecedor alternativo como plano B.","owner":"Engenheiro Residente","dueDate":"2026-02-03","status":"aberto"}]'::jsonb,
      'clientDecisions', '[]'::jsonb
    )
    WHERE project_id = 'fc1eb067-a7d9-41e1-bd39-1845e750c3b7' AND week_number = 2;

  -- Week 3
  UPDATE public.weekly_reports SET data = data
    || jsonb_build_object(
      'lookaheadTasks', '[{"id":"b1c2824e-539c-4a76-8ea0-d3a47d1c3aed","date":"2026-02-09","description":"Início da instalação do forro de gesso drywall nas áreas sociais (sala e varanda).","prerequisites":"Conclusão das instalações elétricas e hidrossanitárias internas no teto.","responsible":"Equipe de Drywall","risk":"médio","riskReason":"Atraso na entrega do material ou complexidade no desenho do forro."},{"id":"65713b6f-7b80-40f9-bdef-151e27d7ef5f","date":"2026-02-10","description":"Verificação final e teste de estanqueidade das prumadas e pontos hidrossanitários.","prerequisites":"Conclusão da instalação dos tubos e conexões hidrossanitárias.","responsible":"Encanador Chefe","risk":"baixo","riskReason":"Pequenos vazamentos facilmente corrigíveis."},{"id":"b75671d1-a203-45d2-8b63-7502cf973c7d","date":"2026-02-11","description":"Preparação da superfície para impermeabilização nos banheiros e área de serviço.","prerequisites":"Reboco e nivelamento concluídos.","responsible":"Equipe de Acabamento","risk":"baixo","riskReason":"Dependência da cura do reboco."},{"id":"0a6f953f-9c1c-4b51-a860-59a247090f2b","date":"2026-02-13","description":"Início da aplicação da impermeabilização em áreas molhadas.","prerequisites":"Superfícies preparadas e secas.","responsible":"Equipe de Acabamento","risk":"baixo","riskReason":"Variações climáticas podem atrasar a cura."}]'::jsonb,
      'risksAndIssues', '[{"id":"53064892-d486-4711-acf5-bd04d694e881","type":"risco","title":"Atraso na entrega de peças de forro gesso customizadas","description":"Possibilidade de atraso na fabricação de placas de gesso com recortes para o projeto luminotécnico.","impact":{"time":"médio","cost":"baixo","quality":"baixo"},"severity":"média","actionPlan":"Confirmar prazos com fornecedor e priorizar áreas não customizadas.","owner":"Eng. Civil Júnior","dueDate":"2026-02-13","status":"em acompanhamento"},{"id":"ccc77a6e-d0f7-480d-a4c8-36a12483c266","type":"impedimento","title":"Aprovação pendente do detalhamento de nichos no banheiro","description":"O projeto executivo dos nichos embutidos no box do banheiro social ainda não foi aprovado pelo cliente.","impact":{"time":"médio","cost":"baixo","quality":"baixo"},"severity":"média","actionPlan":"Agendar reunião de aprovação com o cliente o mais breve possível.","owner":"Arquiteto Responsável","dueDate":"2026-02-12","status":"aberto"}]'::jsonb,
      'clientDecisions', '[]'::jsonb
    )
    WHERE project_id = 'fc1eb067-a7d9-41e1-bd39-1845e750c3b7' AND week_number = 3;

  -- Week 4
  UPDATE public.weekly_reports SET data = data
    || jsonb_build_object(
      'lookaheadTasks', '[{"id":"04de36cc-a106-457f-a0d4-4b6da75ec4f7","date":"2026-02-16","description":"Instalação final das louças e metais sanitários (banheiros e lavabo).","prerequisites":"Conclusão da 1ª demão de pintura e impermeabilização.","responsible":"Equipe de Hidráulica e Acabamento","risk":"médio","riskReason":"Disponibilidade de itens específicos do projeto."},{"id":"4e583160-65e4-4ae0-8b58-b03da53726ff","date":"2026-02-17","description":"Revisão e limpeza grossa de todas as áreas (pré-pintura final).","prerequisites":"Instalação das louças concluída.","responsible":"Equipe de Limpeza","risk":"baixo","riskReason":"Sem riscos significativos."},{"id":"171e708c-acf7-45b6-b1e1-cc65c00a2a2b","date":"2026-02-18","description":"Pintura Geral - 2ª Demão e retoques finais.","prerequisites":"Superfícies limpas e preparadas.","responsible":"Equipe de Pintura","risk":"baixo","riskReason":"Possíveis pequenos reparos antes da demão final."},{"id":"7538b3f9-1a60-4790-aa66-b53907ef3d8d","date":"2026-02-19","description":"Instalação da iluminação decorativa e pontos de luz específicos.","prerequisites":"Pintura final concluída.","responsible":"Equipe de Elétrica","risk":"médio","riskReason":"Atraso na entrega de luminárias personalizadas."}]'::jsonb,
      'risksAndIssues', '[{"id":"b3e60a82-715c-4e09-9925-44b8c4839e8b","type":"risco","title":"Atraso na entrega de luminárias decorativas","description":"Fornecedor das luminárias decorativas informou possível atraso de 3 dias na entrega.","impact":{"time":"médio","cost":"baixo","quality":"baixo"},"severity":"média","actionPlan":"Contatar fornecedor para data atualizada e considerar substituição emergencial.","owner":"Eng. Civil","dueDate":"2026-02-17","status":"em acompanhamento"},{"id":"2dcfb091-28aa-414f-a153-2491e54074a8","type":"problema","title":"Vazamento pontual em rosca de louça entregue","description":"Identificado micro-vazamento em uma das roscas do vaso sanitário do banheiro social.","impact":{"time":"baixo","cost":"baixo","quality":"médio"},"severity":"baixa","actionPlan":"Acionar garantia do fornecedor para troca imediata.","owner":"Mestre de Obras","dueDate":"2026-02-16","status":"aberto"}]'::jsonb,
      'clientDecisions', '[]'::jsonb
    )
    WHERE project_id = 'fc1eb067-a7d9-41e1-bd39-1845e750c3b7' AND week_number = 4;

  -- Week 5
  UPDATE public.weekly_reports SET data = data
    || jsonb_build_object(
      'lookaheadTasks', '[{"id":"964cfe58-2681-44f0-8f91-04d4ee2f0c3d","date":"2026-02-24","description":"Preparação da superfície para instalação de piso vinílico (raspagens e nivelamento).","prerequisites":"Secagem completa da pintura.","responsible":"Equipe de Acabamentos Interiores","risk":"médio","riskReason":"Qualidade da preparação impacta diretamente a durabilidade do piso."},{"id":"6b2f0ea5-f0df-4528-84e3-6ca113792c84","date":"2026-02-25","description":"Instalação do piso vinílico nos dormitórios e sala.","prerequisites":"Superfície preparada e nivelada.","responsible":"Equipe de Instalação de Pisos","risk":"baixo","riskReason":"Equipe especializada e material em estoque."},{"id":"5d8e2a41-76e5-42f2-956a-e2eb40366725","date":"2026-02-26","description":"Revisão e retoques finais na pintura após instalação do piso.","prerequisites":"Piso vinílico instalado.","responsible":"Pintor","risk":"baixo","riskReason":"Atividade de rotina."},{"id":"02c287cc-d2de-47aa-a9d0-804d3e1d7c67","date":"2026-02-27","description":"Instalação de rodapés nos ambientes com piso vinílico.","prerequisites":"Piso curado.","responsible":"Equipe de Acabamentos","risk":"baixo","riskReason":"Atividade sequencial de baixa complexidade."}]'::jsonb,
      'risksAndIssues', '[{"id":"706c5b79-ccda-4d80-9882-129be69a7528","type":"risco","title":"Atraso na entrega de porcelanato para banheiro social","description":"Fornecedor alertou sobre possível atraso de 3 dias devido a problemas logísticos.","impact":{"time":"médio","cost":"baixo","quality":"baixo"},"severity":"média","actionPlan":"Monitoramento diário e fornecedor alternativo como plano B.","owner":"Eng. Civil","dueDate":"2026-02-28","status":"em acompanhamento"},{"id":"4d272b26-8e36-43bb-9aee-bc739d7e8b6b","type":"impedimento","title":"Variação de tonalidade em massa corrida","description":"Variação de tonalidade entre galões de massa corrida pode comprometer a uniformidade da pintura.","impact":{"time":"baixo","cost":"baixo","quality":"médio"},"severity":"baixa","actionPlan":"Segregar lotes e solicitar substituição ao fornecedor.","owner":"Mestre de Obras","dueDate":"2026-02-23","status":"em acompanhamento"}]'::jsonb,
      'clientDecisions', '[]'::jsonb
    )
    WHERE project_id = 'fc1eb067-a7d9-41e1-bd39-1845e750c3b7' AND week_number = 5;

  -- Week 6
  UPDATE public.weekly_reports SET data = data
    || jsonb_build_object(
      'lookaheadTasks', '[{"id":"8bbb0e79-7d51-4830-9e46-b534386881e7","date":"2026-03-02","description":"Configurar e testar hidrômetros e sistema de aquecimento a gás.","prerequisites":"Instalação finalizada de todos os pontos hidráulicos.","responsible":"Encanador Especializado","risk":"médio","riskReason":"Atrasos na entrega de equipamentos ou falhas nos testes."},{"id":"007b2838-b03b-454f-b6bf-d51c98dc15a9","date":"2026-03-03","description":"Preparar superfícies para massa corrida, lixamento e primeira demão de pintura.","prerequisites":"Áreas com contrapiso finalizado.","responsible":"Equipe de Pintura","risk":"baixo","riskReason":"Qualidade do substrato é essencial."},{"id":"7c55f270-e2b6-4bee-9361-46cae4ecb05b","date":"2026-03-05","description":"Início da instalação de forro de gesso e sancas nos ambientes sociais.","prerequisites":"Instalações elétricas de forro concluídas.","responsible":"Gesseiro","risk":"médio","riskReason":"Necessidade de cura do gesso pode atrasar a pintura."},{"id":"648bca25-f68f-4468-9c43-2613d262f47c","date":"2026-03-06","description":"Verificação final da estanqueidade do box dos banheiros.","prerequisites":"Impermeabilização e revestimentos concluídos.","responsible":"Encarregado da Obra","risk":"alto","riskReason":"Falhas neste estágio geram retrabalho significativo."}]'::jsonb,
      'risksAndIssues', '[{"id":"b44c383d-ec3f-4f23-85b5-d36a35b20483","type":"risco","title":"Atraso na entrega de luminárias decorativas importadas","description":"Possível atraso de 2 semanas devido a logística internacional.","impact":{"time":"alto","cost":"baixo","quality":"baixo"},"severity":"alta","actionPlan":"Buscar frete expresso ou antecipar luminárias standard para áreas não críticas.","owner":"Engenheiro Responsável","dueDate":"2026-03-08","status":"em acompanhamento"},{"id":"1f89c2cb-99e3-4b4b-a245-b91d736801b8","type":"impedimento","title":"Aprovação pendente do layout de marcenaria da cozinha","description":"Aprovação final do cliente ainda não obtida, impactando o início da produção.","impact":{"time":"médio","cost":"baixo","quality":"baixo"},"severity":"média","actionPlan":"Agendar reunião de urgência com o cliente.","owner":"Designer de Interiores","dueDate":"2026-03-04","status":"aberto"}]'::jsonb,
      'clientDecisions', '[{"id":"f261fc89-b54c-4b18-a485-6e230bfb3f71","description":"Definição do acabamento e cor dos metais sanitários dos banheiros sociais.","options":["Cobre escovado","Preto fosco","Dourado"],"impactIfDelayed":"Atraso na aquisição e instalação dos metais, comprometendo o cronograma de entrega dos banheiros.","dueDate":"2026-03-03","status":"pending"}]'::jsonb
    )
    WHERE project_id = 'fc1eb067-a7d9-41e1-bd39-1845e750c3b7' AND week_number = 6;

  -- Week 7
  UPDATE public.weekly_reports SET data = data
    || jsonb_build_object(
      'lookaheadTasks', '[{"id":"7a55d300-098d-42a0-bcad-24cfd1b5be1b","date":"2026-03-09","description":"Início da instalação de luminárias nos ambientes principais.","prerequisites":"Pintura concluída e luminárias entregues.","responsible":"Equipe de Elétrica","risk":"médio","riskReason":"Disponibilidade de luminárias específicas."},{"id":"7b55d300-098d-42a0-bcad-24cfd1b5be1c","date":"2026-03-10","description":"Acompanhamento técnico do fechamento da sacada (terceiros).","prerequisites":"Materiais entregues pelo fornecedor.","responsible":"Engenheiro Residente","risk":"alto","riskReason":"Coordenação com terceiros pode gerar atrasos."},{"id":"7c55d300-098d-42a0-bcad-24cfd1b5be1d","date":"2026-03-11","description":"Recebimento de marmoraria e verificação de medidas.","prerequisites":"Conclusão das medições e produção da pedra.","responsible":"Mestre de Obras","risk":"médio","riskReason":"Erro de medição pode comprometer a instalação."},{"id":"7d55d300-098d-42a0-bcad-24cfd1b5be1e","date":"2026-03-13","description":"Conclusão do fechamento da sacada e inspeção final.","prerequisites":"Instalação completa pela equipe terceirizada.","responsible":"Engenheiro Residente","risk":"médio","riskReason":"Possíveis ajustes finais necessários."}]'::jsonb,
      'risksAndIssues', '[{"id":"8a55d300-098d-42a0-bcad-24cfd1b5be1f","type":"risco","title":"Coordenação com terceiros do fechamento da sacada","description":"Empresa terceirizada responsável pelo fechamento de vidro da sacada pode causar atrasos por coordenação inadequada.","impact":{"time":"médio","cost":"baixo","quality":"médio"},"severity":"média","actionPlan":"Reuniões diárias de alinhamento e checklist de interface técnica.","owner":"Engenheiro Residente","dueDate":"2026-03-13","status":"em acompanhamento"},{"id":"8b55d300-098d-42a0-bcad-24cfd1b5be20","type":"problema","title":"Diferença de tom em peças de marmoraria","description":"Lote de marmoraria recebido apresentou diferença de tonalidade entre as peças que serão visíveis nas bancadas.","impact":{"time":"baixo","cost":"médio","quality":"alto"},"severity":"alta","actionPlan":"Solicitar substituição das peças com tonalidade divergente.","owner":"Mestre de Obras","dueDate":"2026-03-10","status":"aberto"}]'::jsonb,
      'clientDecisions', '[{"id":"9a55d300-098d-42a0-bcad-24cfd1b5be21","description":"Aprovação final do modelo do box do banheiro suíte.","options":["Box deslizante","Box pivotante","Box fixo"],"impactIfDelayed":"Atraso na medição e produção do vidro temperado.","dueDate":"2026-03-09","status":"pending"}]'::jsonb
    )
    WHERE project_id = 'fc1eb067-a7d9-41e1-bd39-1845e750c3b7' AND week_number = 7;

  ALTER TABLE public.weekly_reports ENABLE TRIGGER trg_weekly_reports_set_fields;
END;
$outer$;