DO $outer$
BEGIN
  ALTER TABLE public.weekly_reports DISABLE TRIGGER trg_weekly_reports_set_fields;

  -- Week 8
  UPDATE public.weekly_reports SET data = data
    || jsonb_build_object(
      'lookaheadTasks', '[{"id":"a801","date":"2026-03-16","description":"Instalação da marmoraria nas bancadas de cozinha e banheiros.","prerequisites":"Pedras prontas e bases niveladas.","responsible":"Equipe de Marmoraria","risk":"médio","riskReason":"Manuseio de peças pesadas requer atenção."},{"id":"a802","date":"2026-03-17","description":"Conferência elétrica e energização de luminárias instaladas.","prerequisites":"Luminárias montadas e quadros prontos.","responsible":"Equipe de Elétrica","risk":"baixo","riskReason":"Atividade de rotina."},{"id":"a803","date":"2026-03-18","description":"Início da instalação dos boxes de banheiros.","prerequisites":"Marmoraria instalada e medidas confirmadas.","responsible":"Vidraceiro","risk":"médio","riskReason":"Erros de medição podem causar retrabalho."},{"id":"a804","date":"2026-03-20","description":"Limpeza pesada pré-marcenaria.","prerequisites":"Conclusão dos serviços úmidos.","responsible":"Equipe de Limpeza","risk":"baixo","riskReason":"Atividade simples."}]'::jsonb,
      'risksAndIssues', '[{"id":"r801","type":"risco","title":"Atraso na produção da marcenaria","description":"Marcenaria sob medida pode atrasar a entrega final do projeto.","impact":{"time":"alto","cost":"baixo","quality":"baixo"},"severity":"alta","actionPlan":"Acompanhamento semanal com fábrica e visitas técnicas.","owner":"Engenheiro Residente","dueDate":"2026-03-22","status":"em acompanhamento"},{"id":"r802","type":"problema","title":"Pequena infiltração identificada na varanda","description":"Após chuva forte, identificada infiltração pontual no rodapé da varanda.","impact":{"time":"baixo","cost":"baixo","quality":"médio"},"severity":"média","actionPlan":"Refazer impermeabilização localizada e teste de estanqueidade.","owner":"Mestre de Obras","dueDate":"2026-03-19","status":"aberto"}]'::jsonb,
      'clientDecisions', '[]'::jsonb
    )
    WHERE project_id = 'fc1eb067-a7d9-41e1-bd39-1845e750c3b7' AND week_number = 8;

  -- Week 9
  UPDATE public.weekly_reports SET data = data
    || jsonb_build_object(
      'lookaheadTasks', '[{"id":"a901","date":"2026-03-23","description":"Início da instalação da marcenaria modular nos dormitórios.","prerequisites":"Peças entregues e ambientes liberados.","responsible":"Equipe de Marcenaria","risk":"médio","riskReason":"Erros de instalação geram retrabalho caro."},{"id":"a902","date":"2026-03-24","description":"Instalação de espelhos e acessórios em banheiros.","prerequisites":"Pintura e acabamentos finalizados.","responsible":"Vidraceiro","risk":"baixo","riskReason":"Atividade rápida."},{"id":"a903","date":"2026-03-26","description":"Testes de funcionamento dos equipamentos hidráulicos.","prerequisites":"Instalações concluídas.","responsible":"Encanador","risk":"baixo","riskReason":"Pequenas correções esperadas."},{"id":"a904","date":"2026-03-27","description":"Aplicação de selante em juntas de marmoraria.","prerequisites":"Marmoraria assentada.","responsible":"Equipe de Acabamento","risk":"baixo","riskReason":"Atividade rotineira."}]'::jsonb,
      'risksAndIssues', '[{"id":"r901","type":"risco","title":"Atraso entrega de espelhos sob medida","description":"Fornecedor reportou atraso na produção dos espelhos sob medida dos banheiros.","impact":{"time":"médio","cost":"baixo","quality":"baixo"},"severity":"média","actionPlan":"Buscar fornecedor alternativo para garantir entrega.","owner":"Engenheiro Residente","dueDate":"2026-03-26","status":"em acompanhamento"},{"id":"r902","type":"impedimento","title":"Definição final de cores da marcenaria pendente","description":"Cliente ainda não confirmou tonalidade final do laminado da marcenaria da sala.","impact":{"time":"médio","cost":"baixo","quality":"baixo"},"severity":"média","actionPlan":"Reunião imediata com cliente para fechamento.","owner":"Arquiteto","dueDate":"2026-03-25","status":"aberto"}]'::jsonb,
      'clientDecisions', '[]'::jsonb
    )
    WHERE project_id = 'fc1eb067-a7d9-41e1-bd39-1845e750c3b7' AND week_number = 9;

  -- Week 10
  UPDATE public.weekly_reports SET data = data
    || jsonb_build_object(
      'lookaheadTasks', '[{"id":"a1001","date":"2026-03-30","description":"Instalação da marcenaria de cozinha.","prerequisites":"Marmoraria de bancada instalada.","responsible":"Equipe de Marcenaria","risk":"médio","riskReason":"Coordenação com elétricos embutidos."},{"id":"a1002","date":"2026-03-31","description":"Instalação de eletrodomésticos embutidos.","prerequisites":"Marcenaria de cozinha pronta.","responsible":"Técnico Especializado","risk":"baixo","riskReason":"Padronização do fabricante."},{"id":"a1003","date":"2026-04-02","description":"Testes elétricos em todos circuitos.","prerequisites":"Sistema completo energizado.","responsible":"Eletricista Chefe","risk":"baixo","riskReason":"Possíveis ajustes finais."},{"id":"a1004","date":"2026-04-03","description":"Pré-vistoria interna pela equipe técnica.","prerequisites":"Acabamentos concluídos.","responsible":"Engenheiro Residente","risk":"médio","riskReason":"Identificação de pontos a corrigir."}]'::jsonb,
      'risksAndIssues', '[{"id":"r1001","type":"risco","title":"Atraso na entrega do refrigerador","description":"Fornecedor confirmou atraso de 5 dias na entrega do refrigerador embutido.","impact":{"time":"médio","cost":"baixo","quality":"baixo"},"severity":"média","actionPlan":"Manter contato diário e verificar opções alternativas.","owner":"Comprador","dueDate":"2026-04-02","status":"em acompanhamento"},{"id":"r1002","type":"problema","title":"Ajuste necessário em portas de marcenaria","description":"Algumas portas necessitam ajuste de dobradiças para alinhamento perfeito.","impact":{"time":"baixo","cost":"baixo","quality":"médio"},"severity":"baixa","actionPlan":"Marceneiro retornará para ajustes finos.","owner":"Marceneiro","dueDate":"2026-04-01","status":"aberto"},{"id":"r1003","type":"risco","title":"Risco climático para mudança","description":"Previsão de chuva forte na semana de mudança pode afetar transporte.","impact":{"time":"médio","cost":"baixo","quality":"baixo"},"severity":"média","actionPlan":"Coordenação com transportadora para horários alternativos.","owner":"Engenheiro Residente","dueDate":"2026-04-05","status":"aberto"}]'::jsonb,
      'clientDecisions', '[{"id":"d1001","description":"Definição da data oficial da entrega das chaves.","options":["18/04/2026","19/04/2026","20/04/2026"],"impactIfDelayed":"Compromete o agendamento da mudança e finalização contratual.","dueDate":"2026-04-05","status":"pending"}]'::jsonb
    )
    WHERE project_id = 'fc1eb067-a7d9-41e1-bd39-1845e750c3b7' AND week_number = 10;

  -- Week 11
  UPDATE public.weekly_reports SET data = data
    || jsonb_build_object(
      'lookaheadTasks', '[{"id":"a1101","date":"2026-04-06","description":"Conclusão da instalação de marcenaria nos quartos.","prerequisites":"Peças entregues e ambientes liberados.","responsible":"Marceneiro","risk":"baixo","riskReason":"Equipe experiente."},{"id":"a1102","date":"2026-04-07","description":"Instalação dos puxadores e ferragens finais.","prerequisites":"Marcenaria assentada.","responsible":"Marceneiro","risk":"baixo","riskReason":"Atividade simples."},{"id":"a1103","date":"2026-04-09","description":"Limpeza fina de toda a obra.","prerequisites":"Acabamentos finalizados.","responsible":"Equipe de Limpeza","risk":"baixo","riskReason":"Atividade rotineira."},{"id":"a1104","date":"2026-04-10","description":"Vistoria técnica interna pré-cliente.","prerequisites":"Limpeza concluída.","responsible":"Engenheiro Residente","risk":"médio","riskReason":"Identificação de pontos para retrabalho."}]'::jsonb,
      'risksAndIssues', '[{"id":"r1101","type":"problema","title":"Pequenos retoques de pintura necessários","description":"Identificados pontos de retoque após instalação da marcenaria.","impact":{"time":"baixo","cost":"baixo","quality":"médio"},"severity":"baixa","actionPlan":"Equipe de pintura realizará retoques pontuais.","owner":"Pintor","dueDate":"2026-04-09","status":"aberto"},{"id":"r1102","type":"risco","title":"Cobertura de garantias","description":"Necessário organizar e entregar todas as garantias e manuais ao cliente.","impact":{"time":"baixo","cost":"baixo","quality":"alto"},"severity":"média","actionPlan":"Compilar pasta digital e física com toda a documentação.","owner":"Engenheiro Residente","dueDate":"2026-04-12","status":"em acompanhamento"}]'::jsonb,
      'clientDecisions', '[{"id":"d1101","description":"Cliente deseja agendar visita técnica final antes da entrega?","options":["Sim, na semana 12","Sim, na semana 13","Não, apenas vistoria final"],"impactIfDelayed":"Sem impacto significativo, apenas alinhamento de agenda.","dueDate":"2026-04-10","status":"pending"}]'::jsonb
    )
    WHERE project_id = 'fc1eb067-a7d9-41e1-bd39-1845e750c3b7' AND week_number = 11;

  -- Week 12
  UPDATE public.weekly_reports SET data = data
    || jsonb_build_object(
      'lookaheadTasks', '[{"id":"a1201","date":"2026-04-13","description":"Vistoria técnica final com checklist completo.","prerequisites":"Todos os serviços concluídos.","responsible":"Engenheiro Residente","risk":"médio","riskReason":"Identificação de pontos para correção final."},{"id":"a1202","date":"2026-04-14","description":"Correção de eventuais pendências identificadas na vistoria.","prerequisites":"Lista de pendências definida.","responsible":"Mestre de Obras","risk":"médio","riskReason":"Volume de pendências pode variar."},{"id":"a1203","date":"2026-04-16","description":"Limpeza pós-correções e organização final.","prerequisites":"Pendências resolvidas.","responsible":"Equipe de Limpeza","risk":"baixo","riskReason":"Atividade rotineira."},{"id":"a1204","date":"2026-04-17","description":"Preparação da pasta de entrega (manuais, garantias, fotos).","prerequisites":"Documentação compilada.","responsible":"Engenheiro Residente","risk":"baixo","riskReason":"Atividade administrativa."}]'::jsonb,
      'risksAndIssues', '[{"id":"r1201","type":"risco","title":"Possíveis ajustes finais identificados pelo cliente","description":"Cliente pode solicitar pequenos ajustes durante a vistoria pré-entrega.","impact":{"time":"baixo","cost":"baixo","quality":"alto"},"severity":"média","actionPlan":"Manter equipe de plantão para correções imediatas.","owner":"Engenheiro Residente","dueDate":"2026-04-17","status":"em acompanhamento"},{"id":"r1202","type":"impedimento","title":"Aprovação síndico para fim da obra","description":"Necessário formalizar com o condomínio o término oficial da obra.","impact":{"time":"baixo","cost":"baixo","quality":"baixo"},"severity":"baixa","actionPlan":"Enviar comunicado oficial e agendar vistoria do síndico.","owner":"Engenheiro Residente","dueDate":"2026-04-15","status":"aberto"}]'::jsonb,
      'clientDecisions', '[]'::jsonb
    )
    WHERE project_id = 'fc1eb067-a7d9-41e1-bd39-1845e750c3b7' AND week_number = 12;

  -- Week 13
  UPDATE public.weekly_reports SET data = data
    || jsonb_build_object(
      'lookaheadTasks', '[{"id":"a1301","date":"2026-04-20","description":"Entrega oficial das chaves ao cliente.","prerequisites":"Vistoria final aprovada.","responsible":"Engenheiro Residente / Cliente","risk":"baixo","riskReason":"Etapa formal."},{"id":"a1302","date":"2026-04-21","description":"Reunião pós-entrega para feedback do cliente.","prerequisites":"Entrega realizada.","responsible":"CSM / Engenheiro","risk":"baixo","riskReason":"Atividade de relacionamento."},{"id":"a1303","date":"2026-04-22","description":"Início do período de assistência técnica de 90 dias.","prerequisites":"Termo de entrega assinado.","responsible":"Equipe Técnica","risk":"baixo","riskReason":"Suporte pós-obra padrão."},{"id":"a1304","date":"2026-04-24","description":"Encerramento contratual e financeiro do projeto.","prerequisites":"Todas as parcelas quitadas.","responsible":"Financeiro","risk":"baixo","riskReason":"Procedimento administrativo."}]'::jsonb,
      'risksAndIssues', '[{"id":"r1301","type":"risco","title":"Demandas de assistência técnica nos primeiros dias","description":"É comum surgirem pequenos chamados nas primeiras semanas pós-entrega.","impact":{"time":"baixo","cost":"baixo","quality":"alto"},"severity":"média","actionPlan":"Equipe de assistência técnica disponível com SLA de 48h.","owner":"CSM","dueDate":"2026-05-04","status":"em acompanhamento"},{"id":"r1302","type":"problema","title":"Documentação de garantias para entrega","description":"Compilar e entregar pasta completa de garantias e manuais ao cliente.","impact":{"time":"baixo","cost":"baixo","quality":"alto"},"severity":"baixa","actionPlan":"Entrega física e digital no ato da reunião de chaves.","owner":"Engenheiro Residente","dueDate":"2026-04-20","status":"aberto"}]'::jsonb,
      'clientDecisions', '[{"id":"d1301","description":"Confirmação do método de pagamento da última parcela.","options":["Boleto à vista","PIX integral","Transferência bancária"],"impactIfDelayed":"Atrasa o encerramento financeiro do projeto.","dueDate":"2026-04-22","status":"pending"}]'::jsonb
    )
    WHERE project_id = 'fc1eb067-a7d9-41e1-bd39-1845e750c3b7' AND week_number = 13;

  ALTER TABLE public.weekly_reports ENABLE TRIGGER trg_weekly_reports_set_fields;
END;
$outer$;